apiVersion: v1
kind: ReplicationController
metadata:
  name: update-qossort-kitten
spec:
  selector:
    name: update-qossort
    version: kitten
  template:
    metadata:
      labels:
        name: update-qossort
        version: kitten
    spec:
      containers:
      - image: k8s.gcr.io/update-qossort:kitten
        name: update-qossort
        ports:
        - containerPort: 80
          protocol: TCP
